export const message={
    missingFieldMessage: "Please provide all the fields",
    userAlreadyExist: "User already exist",
    userCreatedMessage: "User registered successfully",
    idNotFound: "Id not found",
    userNotFound: "User not found , register first",
    userAlreadyVerified: "User is already verified",
    otpAttemptsExceed: "OTP attempts are exceeded, Please try again after some time",
    otpNotFound: "Please provide an otp",
    otpExpire: "OTP expired, please resend",
    userVerified: "User verified successfully",
    otpSendMessage: "OTP sent successfully",
    userNotVerified: "Please verify your account",
    loginLockedMessage: "Login attempts exceed, Please try again later",
    badAuthMessage: "Invalid name or password",
    loginSuccessful: "Login Successful",
    invalidOtp: "OTP entered is incorrect",
    otpVerified: "OTP verified successfully",
    passwordChange: "Password updated successfully",
    logoutMessage: "Logout successfull",
    unAuthorized: "Please login to access",
    volunteerNotFound: "Volunteer not found, register first",
    volunteerAlreadyVerified: "Volunteer already verified",
    volunteerVerified: "Volunteer verified successfully",
    volunteerNotVerified: "Please verify your account",
    volunteerCreated: "Volunteer created",
    volunteerAlreadyExist: "Volunteer already exist",
    logoutMessage: "Logout successful",

}