export const message={
    missingFieldMessage: "Please provide all the fields",
    userAlreadyExist: "User already exist",
    userCreatedMessage: "User registered successfully",
    idNotFound: "Id not found",
    userNotFound: "User not found , register first",
    userAlreadyVerified: "User is already verified",
    otpAttemptsExceed: "OTP attempts are exceeded, Please try again after some time",
    otpNotFound: "Please provide an otp",
    otpExpire: "OTP expired, please resend",
    userVerified: "User verified successfully",
    otpSendMessage: "OTP sent successfully",
    userNotVerified: "Please verify your account",
    loginLockedMessage: "Login attempts exceed, Please try again later",
    badAuthMessage: "Invalid name or password",
    loginSuccessful: "Login Successful",
    invalidOtp: "OTP entered is incorrect",
    otpVerified: "OTP verified successfully",
    passwordChange: "Password updated successfully",
    logoutMessage: "Logout successful",
    unAuthorized: "Please login to access",
    volunteerNotFound: "Volunteer not found, register first",
    volunteerAlreadyVerified: "Volunteer already verified",
    volunteerVerified: "Volunteer verified successfully",
    volunteerNotVerified: "Please verify your account",
    volunteerCreated: "Volunteer created",
    volunteerAlreadyExist: "Volunteer already exist",
    logoutMessage: "Logout successful",
    userProfileFoundMessage:"User profile fetched",
    userProfileUpdatedMessage:"Profile updated successfully",
    createBlogMessage:"Blog created successfully",
    blogsFetchSuccessfulMessage:"Blogs fetched successfully",
    blogNotFoundMessage:"Blog not found",
    blogDeletedMessage:"Blog deleted successfully",
    blogUpdatedMessage:"Blog updated successfully",
    createReviewMessage:"Review created successfully",
    reviewsFetchSuccessfulMessage:"Reviews fetched successfully",
    createFeedBackMessage:"Feedback created successfully",
    feedBackFetchSuccessfulMessage:"Feedback fetched successfully",
    feedBackDeleteMessage:"Feedback deleted successfully",
    feedBackNotFoundMessage:"Feedback not found",
    contentCreated: "Content created successfullly",
    contentDeletd: "Content Deleted successfully",
    invalidId: "Invalid Id",
    contentFetchSuccessfully: "Content Fetched Successfully",
    contentNotFound: "Content not found",
    contentUpdatedSuccessfully: "Content Updated Successfully"
}